# sakthisaran/portfolio:3 is a arm64 image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: sakthisaran/portfolio:3
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
  - port: 87
    targetPort: 80